language: python
sudo: false

branches:
  except:
    - /^feature/.*$/

python:
  - pypy
  - pypy3
  - "2.7"
  - "3.4"
  - "3.5"

install: travis_retry .travis/install.sh

script: pytest

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository_slug}:%{branch}@%{commit} %{message}"
      - "Duration: %{duration} - Details: %{build_url}"
